'''
=================================================
Milestones 1

Nama  : Daniswara Eka Saputra
Batch : CODA-RMT-002

Program ini dibuat untuk melakukan analisis penjualan produk sepatu pria di website kickavenue.com dengan pengambilan data menggunakan Web Scraping!
=================================================
'''

In [2]:
!pip install selenium bs4

Requirement already satisfied: selenium in c:\users\asus\miniconda3\lib\site-packages (4.26.1)
Requirement already satisfied: bs4 in c:\users\asus\miniconda3\lib\site-packages (0.0.2)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\asus\miniconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.2.3)
Requirement already satisfied: trio~=0.17 in c:\users\asus\miniconda3\lib\site-packages (from selenium) (0.27.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\asus\miniconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\asus\miniconda3\lib\site-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\asus\miniconda3\lib\site-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in c:\users\asus\miniconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: beautifulsoup4 in c:\users\asus\miniconda3\lib\site-packages (from bs4) (4.12.3)
Requirement already satisfied: attrs>=23.2.0 in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (3.7)
Requirement already satisfied: outcome in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (1.17.1)
Requirement already satisfied: exceptiongroup in c:\users\asus\miniconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.2)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\miniconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\asus\miniconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\asus\miniconda3\lib\site-packages (from beautifulsoup4->bs4) (2.6)
Requirement already satisfied: pycparser in c:\users\asus\miniconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\asus\miniconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [3]:
!pip install requests

Requirement already satisfied: requests in c:\users\asus\miniconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\asus\miniconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\asus\miniconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\asus\miniconda3\lib\site-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\asus\miniconda3\lib\site-packages (from requests) (2024.8.30)

In [4]:
from selenium import webdriver
import requests
from bs4 import BeautifulSoup

In [5]:
import pandas as pd

In [14]:
import time

In [15]:
driver = webdriver.Chrome()
# Deklarasi Variable
Nama_Produk = []
harga = []
image = []
link_produk = []


driver.get('https://www.kickavenue.com/search/sneakers?sex=M&sort_by=featured_item_score_desc&keyword=')
SCROLL_PAUSE_TIME = 1.2
# Get scroll height
last_height = driver.execute_script("return document.body.scrollHeight")

while True:
    # Scroll down to bottom
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # Wait to load page
    time.sleep(SCROLL_PAUSE_TIME)

    # Calculate new scroll height and compare with last scroll height
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height == last_height:
        break
    last_height = new_height
time.sleep(20)
html = driver.page_source
soup = BeautifulSoup(html, 'html.parser')   



for data in soup.find_all('div', {'class':'sneaker col-6 col-sm-6 col-md-4 col-lg-3'}): 
    try:
        Nama_Produk.append(data.find('h2', {'class':'price-tag'}).get_text()) # mengambil semua data nama produk
    except:
        Nama_Produk.append(None) # diisi none jika tidak ada data
    try:
        harga.append(data.find('span', {'class':'currency-tag currency-tag__black text-left price-tag text-bold'}).get_text()) # mengambil semua data harga
    except:
        harga.append(None)  # diisi none jika tidak ada data
    try:
        image.append(data.find('img', {'class':'card-img'})['src']) # mengambil semua data image
    except:
        image.append(None)  # diisi none jika tidak ada data
    try:
        link_produk.append(data.find('a', {'target':'_self'})['href']) # mengambil semua data nama link produk
    except:
        link_produk.append(None)  # diisi none jika tidak ada data

In [ ]:
# membuat data frame
df_scrap = pd.DataFrame()

df_scrap['nama_produk'] = Nama_Produk # membuat kolom dari data Nama_Produk
df_scrap['harga'] = harga # membuat kolom dari data harga
df_scrap['gambar'] = image # membuat kolom dari data image
df_scrap['link_produk'] = link_produk # membuat kolom dari data link_produk

In [ ]:
# menghitung jumlah data pada masing2 kolom
print(len(Nama_Produk))
print(len(harga))
print(len(image))
print(len(link_produk))

2527
2527
2527
2527

In [ ]:
df_scrap # memunculkan semua data frame

,nama_produk,harga,gambar,link_produk
0,ASICS Gel-Kayano 14 Cream Black Metallic Plum,"IDR 1,550,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/asics/asics-gel-kayano-14-cream-blac...
1,Nike Dunk Low Cacao Wow (Women's),"IDR 1,200,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-dunk-low-cacao-wow-w-dd150...
2,Air Jordan 1 Low Black Toe Medium Olive,"IDR 1,380,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/air-jordan/air-jordan-1-low-black-to...
3,Nike P-6000 Flat Pewter,"IDR 1,280,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-p-6000-flat-pewter-fn7509-...
4,New Balance 550 White Gum,"IDR 650,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/new-balance-550-white-gu...
...,...,...,...,...
2522,ASICS Magic Speed 2 Ekiden,"IDR 2,770,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/asics/asics-magic-speed-2-ekiden-101...
2523,ASICS Novablast 3 Black Island Blue,"IDR 2,240,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/asics/asics-novablast-3-black-island...
2524,Vans Sk8-Mid 83 DX Anaheim x Neighborhood Black,"IDR 2,140,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/vans/vans-sk8-mid-83-dx-anaheim-x-ne...
2525,Nike Dunk Low Retro PRM Mars Stone,"IDR 1,050,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-dunk-low-retro-prm-mars-st...
2526,Adidas Y-3 Gazelle Off White,"IDR 3,020,000",https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/adidas/adidas-y-3-gazelle-off-white-...

In [ ]:
df_scrap['harga'] = df_scrap['harga'].str.replace('\D', '', regex=True).astype(int) # mengubah type data kolom harga menjadi integer

In [22]:
df_scrap.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2527 entries, 0 to 2526
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nama_produk  2527 non-null   object
 1   harga        2527 non-null   int64
 2   gambar       2527 non-null   object
 3   link_produk  2527 non-null   object
dtypes: int64(1), object(3)
memory usage: 79.1+ KB

In [23]:
df_scrap.columns

Index(['nama_produk', 'harga', 'gambar', 'link_produk'], dtype='object')

In [33]:
df_scrap # data frame setelah diubah kolom harga type datanya

,nama_produk,harga,gambar,link_produk
0,ASICS Gel-Kayano 14 Cream Black Metallic Plum,1550000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/asics/asics-gel-kayano-14-cream-blac...
1,Nike Dunk Low Cacao Wow (Women's),1200000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-dunk-low-cacao-wow-w-dd150...
2,Air Jordan 1 Low Black Toe Medium Olive,1380000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/air-jordan/air-jordan-1-low-black-to...
3,Nike P-6000 Flat Pewter,1280000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-p-6000-flat-pewter-fn7509-...
4,New Balance 550 White Gum,650000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/new-balance-550-white-gu...
...,...,...,...,...
2522,ASICS Magic Speed 2 Ekiden,2770000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/asics/asics-magic-speed-2-ekiden-101...
2523,ASICS Novablast 3 Black Island Blue,2240000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/asics/asics-novablast-3-black-island...
2524,Vans Sk8-Mid 83 DX Anaheim x Neighborhood Black,2140000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/vans/vans-sk8-mid-83-dx-anaheim-x-ne...
2525,Nike Dunk Low Retro PRM Mars Stone,1050000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-dunk-low-retro-prm-mars-st...
2526,Adidas Y-3 Gazelle Off White,3020000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/adidas/adidas-y-3-gazelle-off-white-...

In [ ]:
df_scrap.sort_values(by='harga',ascending=False).head(10) # memunculkan 10 data berdasarkan harga tertinggi

,nama_produk,harga,gambar,link_produk
34,Nike Kobe Zoom 6 Protro EYBL,102600000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kobe-zoom-6-protro-eybl-dm...
1438,Nike Air Foamposite One Paranorman,65070000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-air-foamposite-one-paranor...
1793,Nike Kyrie 3 Luck,63900000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kyrie-3-luck-ar4566-700-ka...
2331,Nike Kyrie 3 Ray Gun,55530000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kyrie-3-ray-gun-ar4567-900...
2019,Nike Kobe 1 Protro DeMar DeRozan,53910000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kobe-1-protro-demar-deroza...
588,Nike Kobe 5 Protro EYBL Tie Dye (2020),46570000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kobe-5-protro-eybl-tie-dye...
1156,Nike Kobe Zoom 7 Barcelona Home,45710000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kobe-zoom-7-barcelona-home...
1064,Nike SB Dunk Low Tweed,41480000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-sb-dunk-low-tweed-304292-2...
1474,Nike Kobe 5 Big Stage Away,41090000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-kobe-5-big-stage-away-3864...
2463,New Balance 990 No Vacancy Inn,34700000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/new-balance-990-no-vacan...

Dari dataframe di atas dapat diketahui bahwa harga tertinggi yang ada pada sneakers men kickavenue yaitu Nike Kobe Zoom 6 Protro EYBL dengan harga 102600000

In [ ]:
df_scrap.sort_values(by='harga',ascending=True).head(10) # memunculkan 10 data berdasarkan harga terendah

,nama_produk,harga,gambar,link_produk
1098,Crep Protect Wipes,100000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/crep-protect/crep-protect-wipes-crep...
554,Crep Protect Pills,100000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/crep-protect/crep-protect-pills-crep...
1287,Porto X Verner Forest Green Slides,199000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/porto-x/porto-x-verner-forest-green-...
2391,Porto X Aalto Beige Flip-Flops,199000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/porto-x/porto-x-aalto-beige-flip-flo...
276,SEJI Low OG Black White,200000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/seji/seji-low-og-black-white-sj-lbwh...
304,Nike Benassi Slides White,250000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-benassi-slides-white-34388...
442,Nike Benassi Slide Black,250000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-benassi-slide-black-343880...
2482,Reebok Classic Slide Black,320000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/reebok/reebok-classic-slide-black-re...
459,Nike Asuna 2 Velvet Brown,340000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-asuna-2-velvet-brown-dc145...
1143,SEJI 2.0 OG Monoblock Ghost Grey,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/seji/seji-20-og-monoblock-ghost-grey...

Dari dataframe di atas dapat diketahui bahwa harga terendah yang ada pada sneakers men kickavenue yaitu Crep Protect Wipes dan Crep Protect Pills dengan harga 100000

In [35]:
df_scrap['harga'].mean()

np.float64(2668366.8381480016)

harga rata-rata sepatu men yang ada di kickavenue yaitu berada pada harga kurang lebih 2670000

In [43]:
df_rekomendasi = df_scrap.query('harga < 500000') #membuat dataframe baru dengan berdasarkan pada harga dibawah 500000
df_rekomendasi

,nama_produk,harga,gambar,link_produk
16,Nike SB Heritage Vulc Black White,450000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-sb-heritage-vulc-black-whi...
37,Nike Ebernon Low Premium 'White Lime Blast',400000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-ebernon-low-premium-white-...
142,Nike Court Vision Low Next Nature White Burgun...,450000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-court-vision-low-next-natu...
180,Nike Court Legacy Next Nature White Photo Blue,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-court-legacy-next-nature-w...
218,Nike Court Vision Low Next Nature White Phantom,400000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-court-vision-low-next-natu...
265,Nike Ebernon Low Triple White,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-ebernon-low-triple-white-w...
276,SEJI Low OG Black White,200000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/seji/seji-low-og-black-white-sj-lbwh...
279,Nike Calm Flip Flops Khaki,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-calm-flip-flops-khaki-fd41...
304,Nike Benassi Slides White,250000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-benassi-slides-white-34388...
328,Nike Legend Essential 3 Next Nature Racer Blue,450000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-legend-essential-3-next-na...
442,Nike Benassi Slide Black,250000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-benassi-slide-black-343880...
459,Nike Asuna 2 Velvet Brown,340000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-asuna-2-velvet-brown-dc145...
460,Nike Roshe One High TDV 'Black',480000,/static/media/kick_avenue_empty_image.cf172573...,/sneakers/nike/nike-roshe-one-high-tdv-black-8...
554,Crep Protect Pills,100000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/crep-protect/crep-protect-pills-crep...
560,Nike Giannis Immortality 3EP Photo Blue,450000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-giannis-immortality-3ep-ph...
581,New Balance 413 V2 Grey,440000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/new-balance-413-v2-grey-...
624,Adidas Predator 20.4 Indoor Sala Boots Black Red,400000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/adidas/adidas-predator-204-indoor-sa...
757,New Balance 411 V3 Black Red,420000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/new-balance-411-v3-black...
882,Converse Chuck Taylor All Star High 70 Vintage...,400000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/converse/converse-chuck-taylor-all-s...
945,Compass Low Gazelle Red Gum,410000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/compass/compass-low-gazelle-red-gum-...
977,New Balance 413 Navy White,420000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/new-balance-413-navy-whi...
1098,Crep Protect Wipes,100000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/crep-protect/crep-protect-wipes-crep...
1143,SEJI 2.0 OG Monoblock Ghost Grey,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/seji/seji-20-og-monoblock-ghost-grey...
1179,Nike Calm Flip Flops Black,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/nike/nike-calm-flip-flops-black-fd41...
1287,Porto X Verner Forest Green Slides,199000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/porto-x/porto-x-verner-forest-green-...
1408,Reebok Flexagon Energy TR 3.0,450000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/reebok/reebok-flexagon-energy-tr-30-...
1515,Converse Chuck Taylor All Star Move Platform S...,450000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/converse/converse-chuck-taylor-all-s...
1817,New Balance 247 Luxe Black (Women's),480000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/new-balance/jordan-jordan-3-retro-bp...
1822,Reebok Energen Lite Black White,360000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/reebok/reebok-energen-lite-black-whi...
1997,Compass Retrograde Low White Blue,480000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/compass/compass-retrograde-low-white...
2021,Reebok Liquifect 90 Navy,410000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/reebok/reebok-liquifect-90-navy-gw49...
2317,Crep Protect Cure Ultimate Cleaning Kit,350000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/crep-protect/crep-protect-cure-ultim...
2391,Porto X Aalto Beige Flip-Flops,199000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/porto-x/porto-x-aalto-beige-flip-flo...
2426,Li-Ning Bubble Slide Paris Fashion Week Red,490000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/li-ning/li-ning-bubble-slide-paris-f...
2482,Reebok Classic Slide Black,320000,https://d5ibtax54de3q.cloudfront.net/eyJidWNrZ...,/sneakers/reebok/reebok-classic-slide-black-re...

Menurut saya sepatu dengan harga terjangkau pada semua kalangan yaitu dibawah harga 500000, berikut data di atas merupakan beberapa data sepatu yang mempunyai harga di bawah 500000, cocok untuk anak muda yang ingin sepatu bagus dengan harga terjangkau.

In [46]:
df_scrap.to_csv('Sneakers_Kick_Avenue.csv', index=False)